apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:latest
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
      ports:
        - containerPort: 27017
